# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://rana454.github.io',
                'git_url': 'https://github.com/rana454/miniai',
                'lib_path': 'miniai'},
  'syms': {'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')}}}
