# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_minibatch_training.ipynb.

# %% auto 0
__all__ = ['accuracy', 'report', 'Dataset']

# %% ../nbs/04_minibatch_training.ipynb 1
import pickle, gzip, os, time, shutil, torch, matplotlib as mpl, numpy as np, matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor, nn 
import torch.nn.functional as F 

# %% ../nbs/04_minibatch_training.ipynb 15
def accuracy(out, yb):
    return (out.argmax(dim=1) == yb).float().mean()

# %% ../nbs/04_minibatch_training.ipynb 16
def report(loss, preds, yb):
    print(f'{loss:.2f}, {accuracy(preds, yb):.2f}')

# %% ../nbs/04_minibatch_training.ipynb 38
class Dataset():
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __len__(self): return len(self.x)
    def __getitem__(self, idx): return self.x[idx], self.y[idx]
